---
- name: Deploy last wishes app to my server
  hosts: localhost
  connection: local
  vars:
    php_version: "7.0"
    symfony_env: prod
    ansistrano_deploy_to: "/usr/home/Arti222/domains/Arti222.usermd.net/public_html"
    ansistrano_deploy_from: "{{ playbook_dir }}"
    ansistrano_deploy_via: "git"
    ansistrano_version_dir: "releases"
    ansistrano_allow_anonymous_stats: no
    ansistrano_keep_releases: 5
    ansistrano_git_repo: git@github.com:Mercurical/jenkins.git
    ansistrano_git_branch: master
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }